#! /bin/sh
pkill sxhkd
sxhkd &
~/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          9

# Color del borde de la ventana que tienes seleccionada (Enfocada)
bspc config focused_border_color "#007BFF"

# Color del borde de las ventanas que están de fondo (Inactivas)
bspc config normal_border_color  "#1a1a1a"

# Color del borde si hay una ventana urgente
bspc config urgent_border_color  "#FF8A65"



bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true

unclutter -idle 1 &
greenclip daemon &

# 1. Quitar la "X" y poner la flecha normal en el fondo
xsetroot -cursor_name left_ptr &

# 2. Forzar el tema de cursor para aplicaciones GTK
export XCURSOR_THEME=Adwaita
